---
title: "Social Media Monitoring Plan"
author: Kay Endriss
date: "September 13, 2018"
output: 
  html_document: 
    theme: cosmo
---

“In preparing for battle I have always found that plans are useless, but planning is indispensable.” 
― Dwight D. Eisenhower

“Always, Always have a plan” 
― Rick Riordan

“The best laid schemes o' mice an' men gang aft agley.” 
― Robert Burns, Collected Poems of Robert Burns

“A man may plant a tree for a number of reasons. Perhaps he likes trees. Perhaps he wants shelter. Or perhaps he knows that someday he may need the firewood.” 
― Joanne Harris, Runemarks

## Setup Before Event to be Monitored ##
* Hurricane Florence

### Accounts to Potentially Monitor ###
* @CityofWS
* @ReadyNC
* @ReadyForsyth
* @cityofwspolice
* @NWSRaleigh
* @NWSBlacksburg
* @NWSGSP
* @NWSWilmingtonNC
* @noticias40 Univision40 - Spanish language
* @NewHanoverEM
* @DukeEnergy

Others to be monitored as needed.

### Main Hashtags (Regular Monitoring) ###
* #FlorenceNC
* #FlorenceNC winston salem
* #FlorenceNC raleigh
* #FlorenceNC wilmington
* #Florence
* #ReadyForsythFlorence


### Additional Hashtags (Sporadic Monitoring) ###
* as needed

### Potential Monitoring Tools ###
* TweetDeck (https://tweetdeck.twitter.com) See helpful info at (https://dgvost.uk/2017/04/tweetdeck/) TweetDeck consists of a series of customisable columns, which can be set up to display the user's Twitter timeline, mentions, direct messages, lists, trends, favorites, search results, hashtags, or all tweets by or to a single user.
* Social Searcher (https://www.social-searcher.com) Social Searcher – Free Social Media Search Engine. It allows to search for content in social networks in real-time and provides deep analytics data. Users can search without logging in for publicly posted information on Twitter, Google+, Facebook, Youtube, Instagram, Tumblr, Reddit, Flickr, Dailymotion and Vimeo. Free users can also save their searches and set up email alerts. Premium Social Monitoring features include: saving social mentions history, exporting data, API integration, advanced analytics, immediate email notifications.
* Facebook Search (https://www.facebook.com/search/all/) 
* Facebook Live Map (https://www.facebook.com/livemap/) The Facebook Live Map is a simple grey map with blue pins indicating where live streams are taking place.
* Tweetreach (https://tweetreach.com) TweetReach Pro is now part of Union Metrics business plans. Monitor social posts across Twitter, Instagram and Facebook, all for the same price as before. Get comprehensive, real-time analytics on reach, performance and engagement, and continuously analyze all posts about the topics you care about, displaying your results in eye-catching charts and digestible reports. 
* Tagboard (https://tagboard.com) Tagboard uses hashtags to search for and collect public social media within seconds of being posted to networks like Twitter, Instagram, and Facebook
* Twitterfall (https://twitterfall.com)Twitterfall is a web-based Twitter client where tweets fall down the screen like a waterfall. Great for presentations and big screen use.
* HootSuite (https://hootsuite.com) Hootsuite is a platform for managing social media. The system’s user interface takes the form of a dashboard, and supports social network integrations for Twitter, Facebook, Instagram, LinkedIn, Google+, YouTube, and many more.
* Advanced Twitter Search (https://twitter.com/search-advanced?lang=en)
* The One Million Tweet Map (http://onemilliontweetmap.com) geo-located tweets only. The one million tweet map is a social media tool that you can use to visualize tweets and aggregated Twitter data on a world map. By using The one million tweet map you can run searches specifying a search term or a hashtag and quickly find a heatmap. It is free and you can use it to find tweets in a map.

I've listed tools somewhat in order of priority for use. It remains to be seen which prove most useful, and how many of these I actually use. Others may assign different priority.

There appeared no need for a separate scheme for collection of important data - just entry into WebEOC seemed best option.
